---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    username:                # Creating user with list
      - piyush
      - raju
      - prajakta

  tasks:
    - name: creating user     # Creating Users
      user:                   # Module name 
        name: "{{ item }}"
        state: present

      loop: "{{ username }}"
      notify: add details in file   # If user get add will save details in files




  handlers:
    - name : add details in file    
      lineinfile:                     # Module name
        path: /root/user_details
        line: "user added"            
        create: yes


